ALTER TABLE `user` ADD UNIQUE(`username`);
ALTER TABLE `user` ADD `mobile` BIGINT UNSIGNED NULL DEFAULT NULL AFTER `email`;
ALTER TABLE `user` CHANGE `email` `email` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
